### ISSUE TITLE
Run azure pipelines NPM deploy only for tagged commits

### ISSUE THREAD

**Issue by domoritz** [vega/ts-json-schema-generator#49]
@chrisrpatterson could you suggest a solution for this? I can't find a condition that says whether a commit is tagged or not. Right now I get errors because I already have a version published on NPM.

**Comment by chrisrpatterson** [comment]
I not sure we have something in the environment that looks at the commit being built and determines if there is a tag on it.  You can trigger on tags so it is possible you could use the fact that the branch is refs/tags instead of refs/heads in your condition.

**Comment by domoritz** [comment]
Thank you, I'll try that. It would be sweet if there was tighter integration with git tags to make releases easier.

**Comment by chrisrpatterson** [comment]
You could probably use a contains function in this condition

https://github.com/vega/ts-json-schema-generator/blob/master/azure-pipelines.yml#L58
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=vsts#contains

I am trying to think about what options there might be to improve that.  In your case it seems you would want to update the triggers section to include triggering on refs/tags and refs/heads

Today you can do this
```
trigger:
  branches:
    include:
      - refs/heads/master
      - refs/tags/*
```
This might be better
```
trigger:
  branches:
    include:
      - refs/heads/master
  tags:
    include:
      - refs/tags/v*
```
and then have a variable automatically set called TagName or something like that.
